### ISSUE TITLE
可以讲一下，这个插件添加并启动以后怎么使用吗

### ISSUE THREAD

**Issue by 73410** [ahdg6/koishi-plugin-mcdev#1]

**Comment by ahdg6** [comment]
你从哪看到的啊，spark跟链接就行

**Comment by ahdg6** [comment]
你启用的时候就会显示注册的指令了

**Comment by ahdg6** [comment]
以后有问题加群问，http://qm.qq.com/cgi-bin/qm/qr?_wv=1027&k=I8ysHWuIuMqHizXEAvL0AycYRschrQbe&authKey=iSCMQ9sDXKZvaUuqSDjciSSmxM1cQnLy3GhhIQnhZTY47vRBTDkgv52NlFU1BJ6L&noverify=0&group_code=957500313
